# 관리자 권한갖기
sudo: required

# 언어(플랫폼) 선택
language: generic

# 도커 환경 구성
services:
  - docker

# 스크립트 실행 환경 구성
before_install:
  - echo "start creating an image with dockerfile"
  - docker build -t chulhee23/docker-react-app -f Dockerfile.dev .

# 실행 스크립트
script:
  - docker run -e CI=true chulhee23/docker-react-app npm run test -- --coverage

# 테스트 성공 후 할 일
after_success:
  - echo "Test Success"

deploy:
  provider: elasticbeanstalk # 외부 서비스 표시
  region: "ap-northeast-2" # 현재 AWS 물리적 장소
  app: "docker-react-app" # 생성된 application 이름
  env: "Dockerreactapp-env"
  bucket_name: "elasticbeanstalk-ap-northeast-2-610947587757" # 해당 eb 위한 s3 버킷 이름
  # travis 에서 가지고 있는 파일을 압축해서 S3로!

  bucket_path: "docker-react-app" # 어플리케이션 이름과 동일
  on:
    branch: master # 어떤 브랜치에 push 할 때 AWS 에 배포를 할 것인지
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  