# 관리자 권한갖기
sudo: required

# 언어(플랫폼) 선택
language: generic

# 도커 환경 구성
services:
  - docker

# 스크립트 실행 환경 구성
before_install:
  - echo "start creating an image with dockerfile"
  - docker build -t chulhee23/docker-react-app -f Dockerfile.dev .

# 실행 스크립트
script:
  - docker run -e CI=true chulhee23/docker-react-app npm run test -- --coverage

# 테스트 성공 후 할 일
after_success:
  - echo "Test Success"